name: Test Project
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code #added comments
        uses: actions/checkout@v4
      # - name: Setup NodeJS
      #   uses: actions/setup-node@v4 #added comments
      #   with:
      #     node-version: 20 
      - name: Install Dependencies  
        run: npm ci
      - name: Run Tests
        run: npm test
    
